version: '{build}'
skip_non_tags: true
image: Visual Studio 2017
build_script:
- ps: |
    .\build.ps1 -raw -skipTests
artifacts:
  - path: '.\src\artifacts\*.nupkg'
deploy:
  provider: NuGet
  server: https://www.myget.org/F/jeremytcd/api/v2
  api_key:
    secure: 0SDurlnu1MdpDZEwbQvG5OGcPy9Nl6ZZNZ6bC3CwB2mBxKpuolxucBOM7XanlQDV
  skip_symbols: false
  artifact: /.*\.nupkg/
cache:
    - '%USERPROFILE%\.nuget\packages -> **\*.csproj'